version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - apt-get update -y
      - apt-get install -y yarn
      - cd frontend
      - yarn install
  pre_build:
    commands:
      - yarn test:unit
  build:
    commands:
      - yarn build --mode=$ENVIRONMENT
  post_build:
    commands:
      - yarn deploy --mode=$ENVIRONMENT && yarn deploy:cleanup --mode=$ENVIRONMENT
