<template>
  <div>
    <b-row>
      <b-col>
        <h2>
          Copy saves to/from original hardware
        </h2>
      </b-col>
    </b-row>
    <div class="blank-line"/>
    <div class="d-none d-md-block"/>
    <b-table
      striped
      responsive="lg"
      :items="items"
      :fields="fields"
      :sort-compare="sortCompare"
      primary-key="index"
      :sort-by="sortBy"
      :sticky-header="$mq | mq({ xs: 'calc(100vh - 4em)', sm: 'calc(100vh - 4em)', md: 'calc(100vh - 4em)', lg: false, xl: false })"
    > <!-- Need a primary key to make sure Vue updates all columns of our table when sorting-->
      <template #cell(hardware)="data">
        <div v-if="data.value.hasOwnProperty('link')">
          <b-link :class="`original-hardware-${data.item.gtmClass}`" :href="data.value.link">{{ data.value.name }}</b-link> <!-- Add in a class for tracking clicks in google tag manager -->
        </div>
        <div v-else>
          {{ data.value.name }}
        </div>
      </template>
      <template #cell()="data">
        <div v-if="typeof data.value === 'string'">
          <!-- Note that we choose a button because we need to render out an <a> element in order for the focus trigger to work for mobile:
          https://bootstrap-vue.org/docs/components/popover#caveats-with-focus-trigger-on-button-elements -->
          <b-button variant="link" :id="`${data.field.key}-${data.item.index}-popover-target`" href="#" tabindex="0">
            <font-awesome-icon :icon="['fas', 'exclamation-triangle']" size="2x" class="supported-with-caveat"/>
          </b-button>
          <b-popover :target="`${data.field.key}-${data.item.index}-popover-target`" triggers="focus hover" placement="bottom">
            {{ data.value }}
          </b-popover>
        </div>
        <div v-else>
          <i :class="data.value ? 'fas fa-check fa-2x supported' : 'fas fa-times fa-2x not-supported'"></i>
        </div>
      </template>
      <template #cell(show_details)="row">
        <div v-if="row.item.hasOwnProperty('software')">
          <b-button size="sm" @click="row.toggleDetails" class="mr-2">
            {{ row.detailsShowing ? 'Less' : 'More'}} info
          </b-button>
        </div>
      </template>
      <template #row-details="row">
        <div :v-if="row.item.software !== undefined">
          <b-card class="text-left">
            <b-row align-h="start">
              <b-col cols="2"/>
              <b-col cols="2"><b>Software:</b></b-col>
              <b-col><b-link :href="row.item.software.link">{{ row.item.software.name }}</b-link></b-col>
            </b-row>
            <div v-if="row.item.software.hasOwnProperty('howToRun')">
              <b-row align-h="start">
                <b-col cols="2"/>
                <b-col cols="2"><b>How to run:</b></b-col>
                <div v-if="row.item.software.hasOwnProperty('howToRunLink')">
                  <b-col><b-link :href="row.item.software.howToRunLink">{{ row.item.software.howToRun }}</b-link></b-col>
                </div>
                <div v-else>
                  <b-col>{{ row.item.software.howToRun }}</b-col>
                </div>
              </b-row>
            </div>
          </b-card>
        </div>
      </template>
      <template #table-caption>
        <p class="contact-info">Anything missing? Found a mistake? Product discontinued? Visit <b-link href="https://discord.gg/wtJ7xUKKTR">https://discord.gg/wtJ7xUKKTR</b-link> or email savefileconverter (at) gmail (dot) com</p>
      </template>
    </b-table>
  </div>
</template>

<style scoped>
.blank-line {
  min-height: 1em;
}

.supported {
  color: green;
}

.not-supported {
  color: lightgrey;
}

.supported-with-caveat {
  color: goldenrod;
}

.contact-info {
  margin-left: 3em;
}

.mydude {
  color: hotpink;
}

</style>

<script>
import {
  BTable,
  BCard,
  BPopover,
} from 'bootstrap-vue';

export default {
  name: 'OriginalHardwareView',
  components: {
    BTable,
    BCard,
    BPopover,
  },
  props: {
    initialSortBy: {
      type: String,
      default: 'hardware',
    },
  },
  methods: {
    sortCompare(aRow, bRow, key, sortDesc, formatter, compareOptions, compareLocale) {
      const a = aRow[key];
      const b = bRow[key];

      // Having a string for a value means "true with caveat" and we want to sort them as if they're true

      const aType = typeof a;
      const bType = typeof b;

      const aBoolean = (aType === 'boolean') || (aType === 'string');
      const bBoolean = (bType === 'boolean') || (bType === 'string');

      const aValue = aBoolean && !!a;
      const bValue = bBoolean && !!b;

      if (aBoolean && bBoolean) {
        if (aValue === bValue) {
          return aRow.hardware.name.localeCompare(bRow.hardware.name, compareLocale, compareOptions); // Sort all of the boolean trues together by name, and the falses by name, so it's easier to read and everything is in a deterministic order
        }

        return aValue ? -1 : 1;
      }

      if (key === 'hardware') {
        return a.name.localeCompare(b.name, compareLocale, compareOptions);
      }

      return 0;
    },
  },
  computed: {
    sortBy() {
      const possibleSortKeys = this.fields.filter((i) => i.sortable).map((i) => i.key);

      if (possibleSortKeys.indexOf(this.initialSortBy) >= 0) {
        return this.initialSortBy;
      }

      return 'hardware';
    },
  },
  data() {
    return {
      fields: [
        {
          key: 'hardware',
          label: 'Hardware',
          sortable: true,
          stickyColumn: true,
        },
        {
          key: 'show_details',
          label: 'More info',
        },
        {
          key: 'nes',
          label: 'NES / FC',
          sortable: true,
        },
        {
          key: 'snes',
          label: 'SNES / SFC',
          sortable: true,
        },
        {
          key: 'n64',
          label: 'N64',
          sortable: true,
        },
        {
          key: 'gcn',
          label: 'GCN',
          sortable: true,
        },
        {
          key: 'gb',
          label: 'GB / GBC',
          sortable: true,
        },
        {
          key: 'gba',
          label: 'GBA',
          sortable: true,
        },
        {
          key: 'lynx',
          label: 'Lynx',
          sortable: true,
        },
        {
          key: 'gamegear',
          label: 'Game Gear',
          sortable: true,
        },
        {
          key: 'sms',
          label: 'SMS',
          sortable: true,
        },
        {
          key: 'genesis',
          label: 'Genesis',
          sortable: true,
        },
        {
          key: 'segacd',
          label: 'Sega CD',
          sortable: true,
        },
        {
          key: 'saturn',
          label: 'Sega Saturn',
          sortable: true,
        },
        {
          key: 'dc',
          label: 'DC',
          sortable: true,
        },
        {
          key: 'tg16',
          label: 'TG-16',
          sortable: true,
        },
        {
          key: 'ps1',
          label: 'PS1',
          sortable: true,
        },
        {
          key: 'ps2',
          label: 'PS2',
          sortable: true,
        },
      ],
      items: [
        {
          index: 0,
          gtmClass: 'retroblaster',
          hardware: {
            name: 'RetroBlaster',
            link: 'https://retrostage.net/?product=retroblaster-programmer-2-0',
          },
          nes: true,
          snes: true,
          n64: true,
          gcn: false,
          gb: true,
          gba: true,
          lynx: false,
          gamegear: false,
          sms: false, // Feb 1, 2022: Not currently possible via a SMS-to-Genesis adapter, although an SMS-specific adapter is in the works
          genesis: true,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: true,
          ps1: false,
          ps2: false,
        },
        {
          index: 1,
          gtmClass: 'retron5',
          hardware: {
            name: 'RetroN 5',
            link: 'https://www.hyperkin.com/retron-5-hd-gaming-console-for-gba-gbc-gb-snes-nes-super-famicom-famicom-genesis-mega-drive-master-system-black-hyperkin.html',
          },
          nes: false, // I never could get this to work with mine, although the device supports NES/FC games
          snes: true,
          n64: false,
          gcn: false,
          gb: true,
          gba: true, // This only partially worked with mine. Some random-seeming games just wouldn't work with it
          lynx: false,
          gamegear: false,
          sms: true, // This is just an assumption, given that you can play SMS games with a SMS-to-Genesis adapter
          genesis: true,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 2,
          gtmClass: 'gb-operator',
          hardware: {
            name: 'GB Operator',
            link: 'https://www.epilogue.co/product/gb-operator',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: true,
          gba: true,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 3,
          gtmClass: 'joey-jr',
          hardware: {
            name: 'Joey Jr.',
            link: 'https://bennvenn.myshopify.com/products/usb-gb-c-cart-dumper-the-joey-jr',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: true,
          gba: true,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 4,
          gtmClass: 'gbxcart-rw',
          hardware: {
            name: 'GBxCart RW',
            link: 'https://www.gbxcart.com/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: true,
          gba: true,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 5,
          gtmClass: 'memcard-pro',
          hardware: {
            name: 'Memcard Pro',
            link: 'https://8bitmods.com/memcard-pro-for-playstation-1-smoke-black/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: true,
          ps2: false,
        },
        {
          index: 6,
          gtmClass: 'retrousb-avs',
          hardware: {
            name: 'RetroUSB AVS',
            link: 'https://www.retrousb.com/product_info.php?products_id=78',
          },
          software: {
            name: 'Scoreboard (under Firmware Downloads)',
            link: 'https://www.retrousb.com/product_info.php?products_id=78',
            howToRun: 'Requires a Windows or Mac computer',
            howToRunLink: 'https://twitter.com/retrousb/status/1154136414247882753?lang=en',
          },
          nes: true,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 7,
          gtmClass: 'retrode2',
          hardware: {
            name: 'Retrode2',
            link: 'https://dragonbox.de/en/cartridge-dumper/retrode2.html',
          },
          nes: false,
          snes: true,
          n64: true,
          gcn: false,
          gb: true,
          gba: true,
          lynx: false,
          gamegear: 'There is a Game Gear adapter for the Retrode, but it has been discontinued and may be difficult to find',
          sms: true,
          genesis: true,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 8,
          gtmClass: 'open-source-cartridge-reader',
          hardware: {
            name: 'Open Source Cartridge Reader',
            link: 'https://github.com/sanni/cartreader',
          },
          nes: true,
          snes: true,
          n64: true,
          gcn: false,
          gb: true,
          gba: true,
          lynx: false,
          gamegear: 'Can use the Retrode SMS + Game Gear adapters, but the Game Gear adapter has been discontinued and may be difficult to find',
          sms: true,
          genesis: true,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 9,
          gtmClass: 'raphnet-n64-adapter',
          hardware: {
            name: 'Raphnet N64-to-USB controller adapter',
            link: 'https://www.raphnet-tech.com/products/n64_usb_adapter_gen3/index.php',
          },
          software: {
            name: 'Raphnet Adapter Manager',
            link: 'https://www.raphnet-tech.com/products/adapter_manager/index.php',
            howToRun: 'Requires a Windows computer',
          },
          nes: false,
          snes: false,
          n64: true,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        /* Feb 3, 2022: Contacted raphnet and they say this cart programmer cannot yet read/write sram although it technically is possible. They say they will be adding this feature soon
        {
          index: 10,
          gtmClass: 'raphnet-cartridge-programmer',
          hardware: {
            name: 'Raphnet cartridge programmer',
            link: 'https://www.raphnet-tech.com/products/sms_cartridge_reader_programmer/index.php',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: true,
          sms: true,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        */
        {
          index: 11,
          gtmClass: 'ps3-memory-card-adapter',
          hardware: {
            name: 'PS3 USB Memory Card Adapter',
            link: 'https://www.psdevwiki.com/ps3/Card_Adapter',
          },
          software: {
            name: 'MemcardRex',
            link: 'https://github.com/ShendoXT/memcardrex/releases',
            howToRun: 'Requires a Windows computer',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: true,
          ps2: false,
        },
        {
          index: 12,
          gtmClass: 'ps1-dexdrive',
          hardware: {
            name: 'PS1 DexDrive',
            link: 'https://en.wikipedia.org/wiki/DexDrive',
          },
          software: {
            name: 'MemcardRex',
            link: 'https://github.com/ShendoXT/memcardrex/releases',
            howToRun: 'Requires a Windows computer',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: true,
          ps2: false,
        },
        {
          index: 13,
          gtmClass: 'playstation2-usb-stick',
          hardware: {
            name: 'PlayStation 2 + USB stick',
            link: 'https://en.wikipedia.org/wiki/PlayStation_2',
          },
          software: {
            name: 'uLaunchElf',
            link: 'http://ps2ulaunchelf.pbworks.com/w/page/19520134/FrontPage',
            howToRun: 'PS2 memory card with Free MCBoot preinstalled',
            howToRunLink: 'https://www.google.com/search?q=ps2+mcboot+memory+card',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: true,
          ps2: true,
        },
        {
          index: 14,
          gtmClass: 'gba-link-cable-dumper-gcn',
          hardware: {
            name: 'GBA + GameCube + GC-to-GBA link cable',
            link: 'https://en.wikipedia.org/wiki/GameCube_%E2%80%93_Game_Boy_Advance_link_cable',
          },
          software: {
            name: 'GBA Link Cable Dumper',
            link: 'https://github.com/FIX94/gba-link-cable-dumper',
            howToRun: 'Various methods for booting homebrew on GameCube',
            howToRunLink: 'https://www.gc-forever.com/wiki/index.php?title=Booting_homebrew',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: true,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 15,
          gtmClass: 'gba-link-cable-dumper-wii',
          hardware: {
            name: 'GBA + Wii + GC-to-GBA link cable',
            link: 'https://en.wikipedia.org/wiki/GameCube_%E2%80%93_Game_Boy_Advance_link_cable',
          },
          software: {
            name: 'GBA Link Cable Dumper',
            link: 'https://github.com/FIX94/gba-link-cable-dumper',
            howToRun: 'Wii softmodding guide',
            howToRunLink: 'https://wii.guide/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: true,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 16,
          gtmClass: 'nintendo-ds-r4',
          hardware: {
            name: 'Nintendo DS + R4 cartridge',
            link: 'https://en.wikipedia.org/wiki/R4_cartridge',
          },
          software: {
            name: 'GBA Backup Tool',
            link: 'https://projectpokemon.org/home/tutorials/save-editing/managing-gba-saves/using-gba-backup-tool-r55/',
            howToRun: 'R4 cartridge',
            howToRunLink: 'https://www.google.com/search?q=best+r4+card+no+timebomb',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: true,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 17,
          gtmClass: 'gcn-gameboy-player',
          hardware: {
            name: 'GameCube + GameBoy Player',
            link: 'https://en.wikipedia.org/wiki/Game_Boy_Player',
          },
          software: {
            name: 'GameBoy Interface',
            link: 'https://www.gc-forever.com/wiki/index.php?title=Game_Boy_Interface#GBA_dumper',
            howToRun: 'Various methods for booting homebrew on GameCube',
            howToRunLink: 'https://www.gc-forever.com/wiki/index.php?title=Booting_homebrew',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: true,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 18,
          gtmClass: 'turbo-everdrive',
          hardware: {
            name: 'Turbo Everdrive',
            link: 'https://krikzz.com/our-products/cartridges/turbo-everdrive-v2.html',
          },
          software: {
            name: 'TEOS Beta4 firmware',
            link: 'https://krikzz.com/forum/index.php?topic=9417.msg71671#msg71671',
            howToRun: 'How to install OS files on Turbo Everdrive',
            howToRunLink: 'https://youtube.com/clip/UgkxzaGhUNm20tYKK8slOsuMqjbYWvJnU3d5',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: true,
          ps1: false,
          ps2: false,
        },
        {
          index: 19,
          gtmClass: '64drive-ultrasave',
          hardware: {
            name: '64drive + UltraSave',
            link: 'http://64drive.retroactive.be/features.php',
          },
          nes: false,
          snes: false,
          n64: true,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 20,
          gtmClass: 'saturn-gamers-cartridge',
          hardware: {
            name: 'Saturn Gamer\'s Cartridge',
            link: 'https://ppcenter.webou.net/satcart/#gamers',
          },
          software: {
            name: 'Pseudo Saturn Kai',
            link: 'https://ppcenter.webou.net/pskai/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: true,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 21,
          gtmClass: 'terraonion-mode-saturn',
          hardware: {
            name: 'Terraonion MODE',
            link: 'https://terraonion.com/en/producto/terraonion-mode/',
          },
          software: {
            name: 'Official firmware update',
            link: 'https://downloads.terraonion.com/shop/product/terraonion-mode-dreamcast-saturn-ode/view',
            howToRun: 'Copy the entire Saturn save RAM, or individual saves',
            howToRunLink: 'https://www.retrorgb.com/mode-saturn-save-restore-backup.html',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: true,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 22,
          gtmClass: 'satiator-ode',
          hardware: {
            name: 'Satiator ODE',
            link: 'https://www.satiator.net/',
          },
          software: {
            name: 'Pseudo Saturn Kai',
            link: 'https://ppcenter.webou.net/pskai/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: true,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 23,
          gtmClass: 'fenrir-ode',
          hardware: {
            name: 'Fenrir ODE',
            link: 'https://www.fenrir-ode.fr/',
          },
          software: {
            name: 'Official firmware',
            link: 'https://www.fenrir-ode.fr/firmware/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: true,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 24,
          gtmClass: 'raphnet-n64-adapter-transfer-pak',
          hardware: {
            name: 'Raphnet N64-to-USB controller adapter + Transfer Pak',
            link: 'https://www.raphnet-tech.com/products/n64_usb_adapter_gen3/index.php',
          },
          software: {
            name: 'Raphnet Adapter Manager',
            link: 'https://www.raphnet.net/programmation/gcn64tools/index_en.php#8',
            howToRun: 'Requires a Windows computer',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: true,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 25,
          gtmClass: 'gamecube-sd-adapter',
          hardware: {
            name: 'GameCube + SD card adapter',
            link: 'https://www.google.com/search?q=gamecube+sd+card+adapter',
          },
          software: {
            name: 'GameCube Memory Manager',
            link: 'https://wiibrew.org/wiki/GameCube_Memory_Manager',
            howToRun: 'Various methods for booting homebrew on GameCube',
            howToRunLink: 'https://www.gc-forever.com/wiki/index.php?title=Booting_homebrew',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: true,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 26,
          gtmClass: 'terraonion-mode-dreamcast',
          hardware: {
            name: 'Terraonion MODE',
            link: 'https://terraonion.com/en/producto/terraonion-mode/',
          },
          software: {
            name: 'VMU Tool',
            link: 'https://bswirl.kitsunet.org/vmutool/release/about/?lg=en&menu=on',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: true,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 27,
          gtmClass: 'gdemu-ode',
          hardware: {
            name: 'GDEmu ODE',
            link: 'https://gdemu.wordpress.com/',
          },
          software: {
            name: 'VMU Tool',
            link: 'https://bswirl.kitsunet.org/vmutool/release/about/?lg=en&menu=on',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: true,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 28,
          gtmClass: 'usb-gdrom-ode',
          hardware: {
            name: 'USB-GDROM ODE',
            link: 'http://3do-renovation.ru/USB-GDROM_Controller.htm',
          },
          software: {
            name: 'VMU Tool',
            link: 'https://bswirl.kitsunet.org/vmutool/release/about/?lg=en&menu=on',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: true,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 29,
          gtmClass: 'memcarduino',
          hardware: {
            name: 'MemCARDuino',
            link: 'http://shendohardware.blogspot.com/2013/06/memcarduino.html',
          },
          software: {
            name: 'MemcardRex',
            link: 'https://github.com/ShendoXT/memcardrex/releases',
            howToRun: 'Requires a Windows computer',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: true,
          ps2: false,
        },
        {
          index: 30,
          gtmClass: 'ps1cardlink',
          hardware: {
            name: 'PS1CardLink',
            link: 'https://github.com/ShendoXT/ps1cardlink',
          },
          software: {
            name: 'MemcardRex',
            link: 'https://github.com/ShendoXT/memcardrex/releases',
            howToRun: 'Requires a Windows computer',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: true,
          ps2: false,
        },
        {
          index: 31,
          gtmClass: 'raphnet-ps1-adapter-multitap',
          hardware: {
            name: 'Raphnet PS1/PS2-to-USB controller adapter + PS1 Multitap',
            link: 'https://www.raphnet-tech.com/products/psx_to_usb/index.php',
          },
          software: {
            name: 'Raphnet Adapter Manager',
            link: 'https://www.raphnet-tech.com/products/adapter_manager/index.php',
            howToRun: 'Requires a Windows computer',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: true,
          ps2: false,
        },
        {
          index: 32,
          gtmClass: 'forever-pak-64',
          hardware: {
            name: 'Forever Pak 64',
            link: 'https://4layertech.com/products/forever-pak-64',
          },
          nes: false,
          snes: false,
          n64: true,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 33,
          gtmClass: 'joey-n64',
          hardware: {
            name: 'Joey N64',
            link: 'https://bennvenn.myshopify.com/products/joeyn64-cart-flasher',
          },
          nes: false,
          snes: false,
          n64: true,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 34,
          gtmClass: 'joey-gg',
          hardware: {
            name: 'Joey GG',
            link: 'https://bennvenn.myshopify.com/products/joeygg-cart-flasher',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: true,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 35,
          gtmClass: 'joey-sms',
          hardware: {
            name: 'Joey SMS',
            link: 'https://bennvenn.myshopify.com/products/joeysms-cart-flasher',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: true,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 36,
          gtmClass: 'joey-lynx',
          hardware: {
            name: 'Joey Lynx',
            link: 'https://bennvenn.myshopify.com/products/joeylynx-cart-flasher',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: true,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 37,
          gtmClass: 'everdrive-64',
          hardware: {
            name: 'Everdrive 64',
            link: 'https://krikzz.com/our-products/cartridges/',
          },
          software: {
            name: 'Official firmware',
            link: 'https://krikzz.com/pub/support/everdrive-64/x-series/OS/',
            howToRun: 'Use the Controller Pak menu',
            howToRunLink: 'https://krikzz.com/pub/support/everdrive-64/x-series/everdrive-64-manual.pdf',
          },
          nes: false,
          snes: false,
          n64: true,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 38,
          gtmClass: 'hyperkin-admiral',
          hardware: {
            name: 'Hyperkin Admiral',
            link: 'https://www.hyperkin.com/admiral-premium-bt-controller-for-n64-white-hyperkin.html',
          },
          nes: false,
          snes: false,
          n64: true,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 39,
          gtmClass: 'gb64-x7',
          hardware: {
            name: 'Everdrive 64 X7 + Transfer Pak',
            link: 'https://krikzz.com/our-products/cartridges/ed64x7.html',
          },
          software: {
            name: 'gb64-x7',
            link: 'https://github.com/ragnaroktomorrow/gb64-x7',
            howToRun: 'Requires a Windows computer',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: true,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 40,
          gtmClass: 'libgbpak',
          hardware: {
            name: 'Everdrive 64 + Transfer Pak',
            link: 'https://krikzz.com/our-products/cartridges/',
          },
          software: {
            name: 'libgbpak',
            link: 'https://github.com/saturnu/libgbpak',
            howToRun: 'Choose to dump SRAM',
            howToRunLink: 'http://micro-64.com/features/gbromdumping.shtml',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: true,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 41,
          gtmClass: 'gameshark-n64',
          hardware: {
            name: 'GameShark N64',
            link: 'https://en.wikipedia.org/wiki/GameShark#Nintendo_64_GameShark',
          },
          software: {
            name: 'The built-in Memory Card Manager',
            link: 'http://www.gametronik.com/site/rubriques/n64/FAQs/Hardware%20-%20GameShark%20Pro%20(U).pdf',
            howToRun: 'Choose to copy a save from a game cartridge to a memory card or vice versa. Only works with EEPROM saves',
          },
          nes: false,
          snes: false,
          n64: true,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 42,
          gtmClass: 'analogue-super-nt',
          hardware: {
            name: 'Analogue Super Nt',
            link: 'https://www.analogue.co/super-nt',
          },
          software: {
            name: 'CopySNES',
            link: 'https://github.com/SmokeMonsterPacks/Super-NT-Jailbreak',
            howToRun: 'Jailbreak the console',
            howToRunLink: 'https://www.joedynamite.com/article/how-to-jailbreak-your-analogue-super-nt/',
          },
          nes: false,
          snes: 'The Analogue Super Nt can only copy saves from a cartridge, and cannot copy saves to a cartridge',
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 43,
          gtmClass: 'analogue-nt-mini',
          hardware: {
            name: 'Analogue Nt Mini',
            link: 'https://www.analogue.co/editions/nt-mini-noir',
          },
          software: {
            name: 'Copy NES mini',
            link: 'https://github.com/SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak',
            howToRun: 'Jailbreak the console',
            howToRunLink: 'https://www.mountainouswords.com/mountain-air/dump-nes-roms-copynes-on-the-nt-mini-noir/',
          },
          nes: 'The Analogue Nt Mini can only copy saves from a cartridge, and cannot copy saves to a cartridge',
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 44,
          gtmClass: 'copynes',
          hardware: {
            name: 'CopyNES',
            link: 'https://www.retrousb.com/product_info.php?products_id=36',
          },
          nes: true,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 45,
          gtmClass: 'pico-memcard',
          hardware: {
            name: 'PicoMemcard',
            link: 'https://github.com/dangiu/PicoMemcard',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: true,
          ps2: false,
        },
        {
          index: 46,
          gtmClass: 'flashkit-programmer-md',
          hardware: {
            name: 'Flashkit programmer MD',
            link: 'https://krikzz.com/our-products/accessories/flashkitmd.html',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: true,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 47,
          gtmClass: 'gb-save-dumper-n64',
          hardware: {
            name: 'Everdrive 64 X3/X5/X7 + Transfer Pak',
            link: 'https://krikzz.com/our-products/cartridges/',
          },
          software: {
            name: 'GB Save Dumper N64',
            link: 'https://github.com/ner01/gb-save-dumper-n64/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: 'It can only read save files from a cartridge and cannot write save files to a cartridge',
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 48,
          gtmClass: 'dc-vm2',
          hardware: {
            name: 'Dreamcast VM2',
            link: 'https://www.dreammods.net/store/p6/VM2.html',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: true,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 49,
          gtmClass: 'brook-wingman-sd',
          hardware: {
            name: 'Brook Wingman SD',
            link: 'https://www.brookaccessory.com/detail/34308510/',
          },
          software: {
            name: 'Brook Dreamcast VMU Save/Load Tool',
            link: 'https://www.brookaccessory.com/download/Dreamcast/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: true,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 50,
          gtmClass: 'ps3-and-ps3-memory-card-adapter',
          hardware: {
            name: 'PlayStation 3 + PS3 USB Memory Card Adapter',
            link: 'https://www.psdevwiki.com/ps3/Card_Adapter',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: true,
          ps2: true,
        },
        {
          index: 51,
          gtmClass: 'gamecube-wii',
          hardware: {
            name: 'Nintendo Wii',
            link: 'https://en.wikipedia.org/wiki/Wii',
          },
          software: {
            name: 'GameCube Memory Manager',
            link: 'https://wiibrew.org/wiki/GameCube_Memory_Manager',
            howToRun: 'Softmod your Wii',
            howToRunLink: 'https://wii.guide/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: true,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 52,
          gtmClass: 'mega-everdrive-pro',
          hardware: {
            name: 'Mega Everdrive Pro',
            link: 'https://krikzz.com/our-products/cartridges/mega-everdrive-pro.html',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: true,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 53,
          gtmClass: 'turbo-everdrive-pro',
          hardware: {
            name: 'Turbo Everdrive Pro',
            link: 'https://krikzz.com/our-products/cartridges/turbo-everdrive-pro.html',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: true,
          ps1: false,
          ps2: false,
        },
        {
          index: 54,
          gtmClass: 'jrodrigo-gameboy-cart-flasher',
          hardware: {
            name: 'J. Rodrigo Gameboy Cart Flasher',
            link: 'https://www.jrodrigo.net/es/project/gameboy-cart-flasher/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: true,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 55,
          gtmClass: 'funnyplaying-burnmaster',
          hardware: {
            name: 'Funnyplaying Burnmaster',
            link: 'https://funnyplaying.com/collections/product/products/portable-cart-flasher-burnmaster',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: true,
          gba: true,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 56,
          gtmClass: 'phoebe-rhea-ode',
          hardware: {
            name: 'Phoebe/Rhea ODE',
            link: 'https://gdemu.wordpress.com/',
          },
          software: {
            name: 'Pseudo Saturn Kai',
            link: 'https://ppcenter.webou.net/pskai/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: true,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 57,
          gtmClass: 'saroo',
          hardware: {
            name: 'Saroo',
            link: 'https://www.segasaturnshiro.com/2024/04/04/i-bought-a-saroo/',
          },
          software: {
            name: 'Official firmware',
            link: 'https://github.com/tpunix/SAROO/releases',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: true,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 58,
          gtmClass: 'memcard-pro-2',
          hardware: {
            name: 'Memcard Pro 2',
            link: 'https://8bitmods.com/memcard-pro2-for-ps2-and-ps1-smoke-black/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: true,
          ps2: true,
        },
        {
          index: 59,
          gtmClass: 'gb-save-manager',
          hardware: {
            name: '2 GB/C or GBA consoles + link cable + flash cart',
            link: 'https://en.wikipedia.org/wiki/Game_Link_Cable',
          },
          software: {
            name: 'Gameboy Save Manager',
            link: 'https://github.com/Gronis/gb-save-manager',
            howToRun: 'Use a flash cartridge',
            howToRunLink: 'https://gbwiki.org/en/other/flashcarts',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: true,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 60,
          gtmClass: 'sd-loader',
          hardware: {
            name: 'SDLoader',
            link: 'https://www.retrorgb.com/new-sega-saturn-sdloader.html',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: true,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 61,
          gtmClass: 'memcard-pro-gc',
          hardware: {
            name: 'Memcard Pro GC',
            link: 'https://8bitmods.com/memcard-pro-gc-for-gamecube-smoke-black/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: true,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: false,
          tg16: false,
          ps1: false,
          ps2: false,
        },
        {
          index: 62,
          gtmClass: 'vmu-pro',
          hardware: {
            name: 'VMU Pro',
            link: 'https://8bitmods.com/vmupro-handheld-visual-memory-card-for-dreamcast-classic-white/',
          },
          nes: false,
          snes: false,
          n64: false,
          gcn: false,
          gb: false,
          gba: false,
          lynx: false,
          gamegear: false,
          sms: false,
          genesis: false,
          segacd: false,
          saturn: false,
          dc: true,
          tg16: false,
          ps1: false,
          ps2: false,
        },
      ],
    };
  },
};
</script>
